/**
 * Created by tqj <2482366539@qq.com> on 2017/8/8.
 */
const db = require('../../db');

module.exports = db.defineModel('monitor', {
    region:{
        type:db.STRING(50),
        allowNull:true
    },
    projectId:db.INTEGER,
    station:{
        type:db.STRING(50),
        allowNull:true
    },
    village:{
        type:db.STRING(50),
        allowNull:true
    },
    group:{
        type:db.STRING(50),
        allowNull:true
    },
    smallClass:{
        type:db.STRING(50),
        allowNull:true
    },
    placeName:{
        type:db.STRING(50),
        allowNull:true
    },
    smallClassArea:{
        type:db.DOUBLE,
        allowNull:true
    },
    treeCompose:{
        type:db.STRING(100),
        allowNull:true
    },
    targetName:{
        type:db.STRING(50),
        allowNull:true
    },
    time:{
        type:db.BIGINT,
        allowNull:true
    },
    treeDensity:db.DOUBLE,
    crownDensity:db.DOUBLE,
});
