/**
 * Created by tqj <2482366539@qq.com> on 2017/8/8.
 */
const db = require('../../db');

module.exports = db.defineModel('supervisor', {
    region:{
        type:db.STRING(50),
        allowNull:true
    },
    station:{
        type:db.STRING(50),
        allowNull:true
    },
    village:{
        type:db.STRING(50),
        allowNull:true
    },
    group:{
        type:db.STRING(50),
        allowNull:true
    },
    smallClass:{
        type:db.STRING(50),
        allowNull:true
    },
    queryName:{
        type:db.STRING(50),
        allowNull:true
    },
    placeName:{
        type:db.STRING(50),
        allowNull:true
    },
    smallClassArea:{
        type:db.DOUBLE,
        allowNull:true
    },
    treeCompose:{
        type:db.STRING(100),
        allowNull:true
    },
    targetName:{
        type:db.STRING(50),
        allowNull:true
    },
    startTime:{
        type:db.STRING(20),
        allowNull:true
    },
    endTime:{
        type:db.STRING(20),
        allowNull:true
    },
    confirmTime:{
        type:db.BIGINT,
        allowNull:true
    },
    rectificationTime:{
        type:db.BIGINT,
        allowNull:true
    },
    projectId:{
        type:db.BIGINT,
        allowNull:true
    },
    workGroupId:{
        type:db.INTEGER,
        allowNull:true
    },
    memberId:{
        type:db.INTEGER,
        allowNull:true
    },
    workQuality:{
        type:db.INTEGER,
        allowNull:true
    },
    mainQuestion:{
        type:db.STRING(50),
        allowNull:true
    },
    effect:{
        type:db.STRING(50),
        allowNull:true
    },
    step:{
        type:db.INTEGER,
        allowNull:true
    }
});
